development:
  adapter: postgresql
  encoding: unicode
  database: stashkevich_development
  pool: 15
test:
  adapter: postgresql
  encoding: unicode
  database: stashkevich_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: stashkevich_production
  pool: 15
  username: stashkevich
  password: 6yFC7HYW6FErhu6JQ
